---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "nexus"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - image: "fabric8/nexus3:test"
        imagePullPolicy: "IfNotPresent"
        lifecycle:
          postStart:
            exec:
              command:
              - "/opt/sonatype/nexus/postStart.sh"
        readinessProbe:
          httpGet:
            path: "/"
            port: 8081
          initialDelaySeconds: 60
          timeoutSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: "/"
        #     port: 8081
        #   initialDelaySeconds: 1000
        #   timeoutSeconds: 10
        name: "nexus"
        ports:
        - containerPort: 8081
          name: "http"
        # resources:
        #   limits:
        #     cpu: 0.75
        #     memory: 1G
        #   requests:
        #     cpu: 0.5
        #     memory: 512M
      #   volumeMounts:
      #   - mountPath: "/nexus-data"
      #     name: "nexus-storage"
      #     readOnly: false
      # volumes:
      # - name: "nexus-storage"
      #   persistentVolumeClaim:
      #     claimName: nexus-storage
